spring.profiles.active=dev

spring.application.name=plataforma-pelis
server.servlet.context-path=/plataforma-pelis/api

#PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

#langchain4j
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini